### ISSUE TITLE
Android 10 下载完成后无法安装

### ISSUE THREAD

**Issue by winterfeel** [MZCretin/AutoUpdateProject#23]
小米8安卓10

下载完成后安装闪退，报错：

FATAL EXCEPTION: main
Process: com.xxx.xxx, PID: 17311
    java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/com.xxx.xxx/apks/xxx_7.0.2.apk
        at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
        at com.cretin.www.cretinautoupdatelibrary.utils.AppUtils.installApkFile(AppUtils.java:42)
        at com.cretin.www.cretinautoupdatelibrary.utils.AppUpdateUtils.downloadComplete(AppUpdateUtils.java:421)

貌似是fielprovider的什么错误，我技术太水不会解决，麻烦lz看下

**Comment by gemgao** [comment]
应该是你用androidx的原因吧

**Comment by MZCretin** [comment]
demo能正常运行吗？我这边测试小米8是没有问题的
