### ISSUE TITLE
更新包APK下载完毕，但是拉取安装的步骤崩溃了

### ISSUE THREAD

**Issue by q88qaz** [MZCretin/AutoUpdateProject#50]
2022-10-17 16:21:59.369 17766-17766/com.qs.shabaojs E/【AppUpdateUtils】: 文件下载完成，准备安装，文件地址：/storage/emulated/0/Android/data/com.zbc.abb/cache/com.zbc.abb/apks/新版本_1.0.9.apk
2022-10-17 16:21:59.371 17766-17766/com.qs.shabaojs E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qs.shabaojs, PID: 17766
    java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.zbc.abb/cache/com.zbc.abb/apks/新版本_1.0.9.apk
        at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
        at com.cretin.www.cretinautoupdatelibrary.utils.AppUtils.installApkFile(AppUtils.java:42)
        at com.cretin.www.cretinautoupdatelibrary.utils.AppUpdateUtils.downloadComplete(AppUpdateUtils.java:421)
        at com.cretin.www.cretinautoupdatelibrary.utils.AppUpdateUtils.access$400(AppUpdateUtils.java:53)
        at com.cretin.www.cretinautoupdatelibrary.utils.AppUpdateUtils$1.completed(AppUpdateUtils.java:352)
        at com.liulishuo.filedownloader.FileDownloadMessenger.handoverMessage(FileDownloadMessenger.java:344)
        at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.dispose(FileDownloadMessageStation.java:185)
        at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.handleMessage(FileDownloadMessageStation.java:173)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by Witnin** [comment]
+1
